apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: build-to-quay
  namespace: demo-quay
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/gestrem/pacman:prod'
  pushSecret:
    name: "gestrem-ocp-robot-pull-secret"
  source:
    git:
      ref: master
      uri: 'https://github.com/gestrem/pacman'
    contextDir: /
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi7'
      env: []
  resources: {}
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
 
