apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: example
  namespace: pacman-dev
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/gestrem/pacman'
    contextDir: /
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi7'
      env: []
      output:
       to:
        kind: DockerImage
        name: 'quay.io/gestrem/pacman:dev'
        
  resources: {}
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange

spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'pacman:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi7'
