apiVersion: v1
kind: Secret
metadata:
  name: demo-pacman-ocp-robot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LTMwNjMuYXBwcy5zaGFyZWQtcmhwZHM0LnJocGRzNC5vcGVuc2hpZnQub3BlbnRsYy5jb20iOiB7CiAgICAgICJhdXRoIjogIlpHVnRieTF3WVdOdFlXNHJiMk53WDNKdlltOTBPazB3TVRGVVRVRlpVMFpOUzAxWE1GRlJPREZEVUZWTk1GRkdORGhJT0RRNVJWWk5TMVZUUlRkQ1VqY3dUMWhFUWpJNVVqZEdSRkpNTmxNeE5VNUlVVUU9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson