apiVersion: v1
kind: Secret
metadata:
  name: goldenimages-robot-team1-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LXJlZ2lzdHJ5LXF1YXktcXVheS1lbnRlcnByaXNlLmFwcHMuY2x1c3Rlci0xNWFkLjE1YWQuc2FuZGJveDQyMi5vcGVudGxjLmNvbSI6IHsKICAgICAgImF1dGgiOiAiWjI5c1pHVnVhVzFoWjJWekszSnZZbTkwWDNSbFlXMHhPazFHVWpoVVFVUTRTemxFVUZsV1RFRldTbEJaVVZneVRqQkpPVlpNVWxCVFFWQlFVVlpNVkRoWlVrNUpTRll5VTBsWVZFRlZTRGhQVUVWV1ZqWkhXRlk9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson