apiVersion: v1
kind: Secret
metadata:
  name: gestrem-ocp-robot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaMlZ6ZEhKbGJTdHZZM0JmY205aWIzUTZVekpFUzBGT05rUklUVFZYTmtWVU1UQk9WbE5KVFVZM09GZFlUalZDVVRGV1FVeEdWalJGV1U0MFUxWlhVVUUxU2xWWFVUZElNRkV4TTBsSlRsRTFNUT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson