apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2021-01-04T14:40:52Z'
  generation: 17
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2021-01-05T13:24:41Z'
  name: new-pipeline
  namespace: pacman-dev
  resourceVersion: '358431'
  selfLink: /apis/tekton.dev/v1beta1/namespaces/pacman-dev/pipelines/new-pipeline
  uid: 63ec8593-d836-4d8a-9e50-4f82c1a83893
spec:
  tasks:
    - name: s2i-nodejs
      params:
        - name: VERSION
          value: '12'
        - name: PATH_CONTEXT
          value: /
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: 'quay.io/gestrem/pacman:dev'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-nodejs
      workspaces:
        - name: output
          workspace: source
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/gestrem/pacman.git'
        - name: revision
          value: master
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
  workspaces:
    - name: source
